---
- name: Upgrade all & install python2 if needed
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || test -e /usr/bin/python3 || apt-get install -y python-minimal
      changed_when: false
