---
- name: Install MongoDB
  hosts: all
  become: true

  tasks:
    - name: Add apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.6.asc
        state: present

    - name: Add apt repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
        state: present

    - name: Upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install mongodb-org package
      apt:
        name: mongodb-org
        state: present

    - name: Enable mongod
      systemd:
        name: mongod
        enabled: yes
