---
- name: Configure App
  hosts: app
  become: true

  vars:
    db_host: "{{ hostvars[groups['db'][0]]['internal_ip'] | default(hostvars[groups['db'][0]]['ansible_default_ipv4']['address']) | default(hostvars[groups['db'][0]]['ansible_all_ipv4_addresses'][0]) | default('127.0.0.1') }}:27017"

  roles:
    - app
