---
- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: "{{ hostvars[groups['db'][0]]['internal_ip'] | default( hostvars[groups['db'][0]]['ansible_default_ipv4']['address'] | default( hostvars[groups['db'][0]]['ansible_all_ipv4_addresses'][0] | default('127.0.0.1') ) ) }}:27017"

  tasks:
    - debug:
        var: db_host

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=reloaded
