---
- name: Configure MongoDB
  hosts: db
  become: true
  vars:
    mongo_bind_ip: "{{ db_internal_ip }}"

  tasks:
    - debug:
        var: mongo_bind_ip

    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted
