---
- name: Install Ruby and Bundler
  hosts: all
  become: true

  tasks:
    - name: Upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
        state: present
